apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-python
spec:
  selector:
     project: {{ .Release.Name }}-web-python
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer